/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AutenticacaoRouteRouteImport } from './routes/autenticacao/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AutenticacaoCadastreSeRouteImport } from './routes/autenticacao/cadastre-se'
import { Route as AutenticacaoEsqueciMinhaSenhaRouteImport } from './routes/autenticacao/esqueci-minha-senha'
import { Route as AutenticacaoLoginRouteImport } from './routes/autenticacao/login'
import { Route as AutenticacaoResetSenhaRouteImport } from './routes/autenticacao/reset-senha'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticacaoRouteRoute = AutenticacaoRouteRouteImport.update({
  id: '/autenticacao',
  path: '/autenticacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AutenticacaoCadastreSeRoute = AutenticacaoCadastreSeRouteImport.update({
  id: '/cadastre-se',
  path: '/cadastre-se',
  getParentRoute: () => AutenticacaoRouteRoute,
} as any)
const AutenticacaoEsqueciMinhaSenhaRoute =
  AutenticacaoEsqueciMinhaSenhaRouteImport.update({
    id: '/esqueci-minha-senha',
    path: '/esqueci-minha-senha',
    getParentRoute: () => AutenticacaoRouteRoute,
  } as any)
const AutenticacaoLoginRoute = AutenticacaoLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AutenticacaoRouteRoute,
} as any)
const AutenticacaoResetSenhaRoute = AutenticacaoResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => AutenticacaoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/autenticacao': typeof AutenticacaoRouteRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/autenticacao/cadastre-se': typeof AutenticacaoCadastreSeRoute
  '/autenticacao/esqueci-minha-senha': typeof AutenticacaoEsqueciMinhaSenhaRoute
  '/autenticacao/login': typeof AutenticacaoLoginRoute
  '/autenticacao/reset-senha': typeof AutenticacaoResetSenhaRoute
}
export interface FileRoutesByTo {
  '/autenticacao': typeof AutenticacaoRouteRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/autenticacao/cadastre-se': typeof AutenticacaoCadastreSeRoute
  '/autenticacao/esqueci-minha-senha': typeof AutenticacaoEsqueciMinhaSenhaRoute
  '/autenticacao/login': typeof AutenticacaoLoginRoute
  '/autenticacao/reset-senha': typeof AutenticacaoResetSenhaRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/autenticacao': typeof AutenticacaoRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/autenticacao/cadastre-se': typeof AutenticacaoCadastreSeRoute
  '/autenticacao/esqueci-minha-senha': typeof AutenticacaoEsqueciMinhaSenhaRoute
  '/autenticacao/login': typeof AutenticacaoLoginRoute
  '/autenticacao/reset-senha': typeof AutenticacaoResetSenhaRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autenticacao'
    | '/dashboard'
    | '/autenticacao/cadastre-se'
    | '/autenticacao/esqueci-minha-senha'
    | '/autenticacao/login'
    | '/autenticacao/reset-senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/autenticacao'
    | '/dashboard'
    | '/autenticacao/cadastre-se'
    | '/autenticacao/esqueci-minha-senha'
    | '/autenticacao/login'
    | '/autenticacao/reset-senha'
    | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/autenticacao'
    | '/_protected/dashboard'
    | '/autenticacao/cadastre-se'
    | '/autenticacao/esqueci-minha-senha'
    | '/autenticacao/login'
    | '/autenticacao/reset-senha'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AutenticacaoRouteRoute: typeof AutenticacaoRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autenticacao': {
      id: '/autenticacao'
      path: '/autenticacao'
      fullPath: '/autenticacao'
      preLoaderRoute: typeof AutenticacaoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/autenticacao/cadastre-se': {
      id: '/autenticacao/cadastre-se'
      path: '/cadastre-se'
      fullPath: '/autenticacao/cadastre-se'
      preLoaderRoute: typeof AutenticacaoCadastreSeRouteImport
      parentRoute: typeof AutenticacaoRouteRoute
    }
    '/autenticacao/esqueci-minha-senha': {
      id: '/autenticacao/esqueci-minha-senha'
      path: '/esqueci-minha-senha'
      fullPath: '/autenticacao/esqueci-minha-senha'
      preLoaderRoute: typeof AutenticacaoEsqueciMinhaSenhaRouteImport
      parentRoute: typeof AutenticacaoRouteRoute
    }
    '/autenticacao/login': {
      id: '/autenticacao/login'
      path: '/login'
      fullPath: '/autenticacao/login'
      preLoaderRoute: typeof AutenticacaoLoginRouteImport
      parentRoute: typeof AutenticacaoRouteRoute
    }
    '/autenticacao/reset-senha': {
      id: '/autenticacao/reset-senha'
      path: '/reset-senha'
      fullPath: '/autenticacao/reset-senha'
      preLoaderRoute: typeof AutenticacaoResetSenhaRouteImport
      parentRoute: typeof AutenticacaoRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AutenticacaoRouteRouteChildren {
  AutenticacaoCadastreSeRoute: typeof AutenticacaoCadastreSeRoute
  AutenticacaoEsqueciMinhaSenhaRoute: typeof AutenticacaoEsqueciMinhaSenhaRoute
  AutenticacaoLoginRoute: typeof AutenticacaoLoginRoute
  AutenticacaoResetSenhaRoute: typeof AutenticacaoResetSenhaRoute
}

const AutenticacaoRouteRouteChildren: AutenticacaoRouteRouteChildren = {
  AutenticacaoCadastreSeRoute: AutenticacaoCadastreSeRoute,
  AutenticacaoEsqueciMinhaSenhaRoute: AutenticacaoEsqueciMinhaSenhaRoute,
  AutenticacaoLoginRoute: AutenticacaoLoginRoute,
  AutenticacaoResetSenhaRoute: AutenticacaoResetSenhaRoute,
}

const AutenticacaoRouteRouteWithChildren =
  AutenticacaoRouteRoute._addFileChildren(AutenticacaoRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AutenticacaoRouteRoute: AutenticacaoRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
