import type { IconType } from "react-icons";
import {
  TbBabyCarriage,
  TbBallFootball,
  TbBarbell,
  TbBasket,
  TbBeach,
  TbBeer,
  TbBike,
  TbBolt,
  TbBook,
  TbBriefcase,
  TbBuildingBank,
  TbBus,
  TbCalendar,
  TbCar,
  TbCash,
  TbChartLine,
  TbCoffee,
  TbCoin,
  TbCreditCard,
  TbDeviceDesktop,
  TbDeviceGamepad2,
  TbDeviceMobile,
  TbDroplet,
  TbFileInvoice,
  TbFirstAidKit,
  TbFlame,
  TbGasStation,
  TbGift,
  TbHeart,
  TbHeartbeat,
  TbHome,
  TbMovie,
  TbMusic,
  TbPaw,
  TbPhone,
  TbPigMoney,
  TbPill,
  TbPizza,
  TbPlane,
  TbReceipt,
  TbRepeat,
  TbSchool,
  TbScissors,
  TbShirt,
  TbShoppingCart,
  TbStar,
  TbStethoscope,
  TbTag,
  TbTool,
  TbToolsKitchen2,
  TbTrain,
  TbUsers,
  TbWallet,
  TbWifi,
} from "react-icons/tb";

export type TagIcon = {
  label: string;
  icon: IconType;
};

// Keys are stored in the tag's "icon" column (the API accepts any alphanumeric key up to 30 chars).
export const TagIcons: Record<string, TagIcon> = {
  tag: { label: "Etiqueta", icon: TbTag },
  home: { label: "Casa", icon: TbHome },
  car: { label: "Carro", icon: TbCar },
  fuel: { label: "Combustível", icon: TbGasStation },
  bus: { label: "Ônibus", icon: TbBus },
  train: { label: "Trem", icon: TbTrain },
  bike: { label: "Bicicleta", icon: TbBike },
  plane: { label: "Viagem", icon: TbPlane },
  beach: { label: "Férias", icon: TbBeach },
  cart: { label: "Compras", icon: TbShoppingCart },
  basket: { label: "Mercado", icon: TbBasket },
  restaurant: { label: "Restaurante", icon: TbToolsKitchen2 },
  coffee: { label: "Café", icon: TbCoffee },
  pizza: { label: "Lanche", icon: TbPizza },
  beer: { label: "Bar", icon: TbBeer },
  health: { label: "Saúde", icon: TbHeartbeat },
  firstaid: { label: "Primeiros socorros", icon: TbFirstAidKit },
  pill: { label: "Farmácia", icon: TbPill },
  doctor: { label: "Médico", icon: TbStethoscope },
  school: { label: "Educação", icon: TbSchool },
  book: { label: "Livros", icon: TbBook },
  work: { label: "Trabalho", icon: TbBriefcase },
  bank: { label: "Banco", icon: TbBuildingBank },
  creditcard: { label: "Cartão de crédito", icon: TbCreditCard },
  cash: { label: "Dinheiro", icon: TbCash },
  coin: { label: "Moedas", icon: TbCoin },
  savings: { label: "Poupança", icon: TbPigMoney },
  wallet: { label: "Carteira", icon: TbWallet },
  receipt: { label: "Recibo", icon: TbReceipt },
  invoice: { label: "Fatura", icon: TbFileInvoice },
  investment: { label: "Investimentos", icon: TbChartLine },
  subscription: { label: "Assinatura", icon: TbRepeat },
  calendar: { label: "Calendário", icon: TbCalendar },
  gift: { label: "Presente", icon: TbGift },
  clothes: { label: "Roupas", icon: TbShirt },
  phone: { label: "Telefone", icon: TbPhone },
  mobile: { label: "Celular", icon: TbDeviceMobile },
  computer: { label: "Computador", icon: TbDeviceDesktop },
  internet: { label: "Internet", icon: TbWifi },
  electricity: { label: "Energia", icon: TbBolt },
  water: { label: "Água", icon: TbDroplet },
  gas: { label: "Gás", icon: TbFlame },
  pet: { label: "Pet", icon: TbPaw },
  baby: { label: "Bebê", icon: TbBabyCarriage },
  family: { label: "Família", icon: TbUsers },
  gym: { label: "Academia", icon: TbBarbell },
  sports: { label: "Esportes", icon: TbBallFootball },
  movie: { label: "Cinema", icon: TbMovie },
  music: { label: "Música", icon: TbMusic },
  games: { label: "Jogos", icon: TbDeviceGamepad2 },
  tools: { label: "Manutenção", icon: TbTool },
  beauty: { label: "Beleza", icon: TbScissors },
  heart: { label: "Favorito", icon: TbHeart },
  star: { label: "Destaque", icon: TbStar },
};
